### ISSUE TITLE
java.io.IOException: setPreviewTexture failed when scanning succesfully and trying to scan again

### ISSUE THREAD

**Issue by GabrielCR99** [pdliuw/ai_barcode#14]
So, I've tested out your package, and it worked fine, I browsed for a lot of packages that scan QR Code, and yours is the best I can use in my Fltutter project, seriouslly!
But unfortunately, I ended up with an Exception that seems to be native Android Exception.
Steps to reproduce:
1. Scanned QR Code, pushed to another page
2. Returned to home page by clicking on button
3. Clicked to scan QR Code again, and then Exception shows up.

To call up the QR code scanner, this is the following code:

`Column(
        children: [
          Expanded(
            child: QrScanner.defaultStyle(
              resultCallback: (final code) async {
                final decodedQrData = jsonDecode(code);
                controller.setValues(
                  favoured: decodedQrData['favoured'],
                  value: decodedQrData['value'],
                );
                await Modular.to.pushNamed('/pay/confirm-page');
              },
            ),
          ),
        ],
      ),
`

### Logs

`E/CameraPreview(20986): java.io.IOException: setPreviewTexture failed
E/CameraPreview(20986): java.io.IOException: setPreviewTexture failed
E/CameraPreview(20986): 	at android.hardware.Camera.setPreviewSurface(Native Method)
E/CameraPreview(20986): 	at android.hardware.Camera.setPreviewDisplay(Camera.java:805)
E/CameraPreview(20986): 	at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:88)
E/CameraPreview(20986): 	at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:73)
E/CameraPreview(20986): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:822)
E/CameraPreview(20986): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:158)
E/CameraPreview(20986): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
E/CameraPreview(20986): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2838)
E/CameraPreview(20986): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
E/CameraPreview(20986): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
E/CameraPreview(20986): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
`

**Comment by pdliuw** [comment]
Maybe it can help you ：https://github.com/pdliuw/ai_barcode/tree/master/example/lib

**Comment by GabrielCR99** [comment]
No, just no. Your example doesn't work. Also, you were rude on closing the issue without even trying to understand what I've done with the qr scanner.
