### ISSUE TITLE
开启主题样式, 会显示空白页

### ISSUE THREAD

**Issue by bulanni00** [pdliuw/ai_barcode#17]
![image](https://user-images.githubusercontent.com/53462035/106406886-46fb0180-646d-11eb-8a6b-5ad96a1ca185.png)
需关闭,才正常

**Comment by pdliuw** [comment]
**请在相应系统上使用相应的系统主题：**

比如：
在Android系统上使用
`
theme: ThemeData(platform: TargetPlatform.android),
`
在iOS系统上使用
`
theme: ThemeData(platform: TargetPlatform.iOS),
`
