### ISSUE TITLE
Migrates to null safety

### ISSUE THREAD

**Issue by alanlanglois** [pdliuw/ai_barcode#19]
One of the only left library I'm using not yet null safety ready. 
Here are some info on how to migrate: 
https://www.youtube.com/watch?v=eBr5tlumwlg
or 
https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by pdliuw** [comment]
> 我正在使用的仅有的左侧库之一尚未准备好安全性。
> 以下是一些有关迁移的信息：
> [https](https://www.youtube.com/watch?v=eBr5tlumwlg) : [//www.youtube.com/watch?v=eBr5tlumwlg](https://www.youtube.com/watch?v=eBr5tlumwlg)
> 或
> [https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null -安全-e550ce72c010](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010)

Thank you very much for your attention

We will improve it as soon as possible

Thank you very much.

**Comment by Elendiar** [comment]
> We will improve it as soon as possible

Thanks you for this plugin, but when nullsafety update released ?

**Comment by radvansky-tomas** [comment]
@pdliuw I've migrated whole project, platform interface and web implementation to null-safety and flutter 2. I might do some more improvements

**Comment by pdliuw** [comment]
* Thank you for your help! 
* merge #26 from @radvansky-tomas ,thank you very much
* null safety #[v3.0.0](https://github.com/pdliuw/ai_barcode/releases/tag/v3.0.0)
