### ISSUE TITLE
How to check error type?

### ISSUE THREAD

**Issue by Project112224** [pdliuw/ai_barcode#20]
this tool is very nice!!, but i don't know  error type or success check method
(success is 200, error is 500?)

now error is "Unable to start scanning This app does not have permission to access the camera"
<img width="745" alt="截圖 2021-03-25 上午10 56 51" src="https://user-images.githubusercontent.com/17908917/112412122-f27f4e80-8d58-11eb-9662-1b4b7c1a12ef.png">
check method is
<img width="785" alt="截圖 2021-03-25 上午10 57 15" src="https://user-images.githubusercontent.com/17908917/112412178-0b87ff80-8d59-11eb-9606-e00cfb0070d5.png">

**Comment by pdliuw** [comment]
> this tool is very nice!!, but i don't know error type or success check method
> (success is 200, error is 500?)
> 
> now error is "Unable to start scanning This app does not have permission to access the camera"
> <img alt="截圖 2021-03-25 上午10 56 51" width="745" src="https://user-images.githubusercontent.com/17908917/112412122-f27f4e80-8d58-11eb-9662-1b4b7c1a12ef.png">
> check method is
> <img alt="截圖 2021-03-25 上午10 57 15" width="785" src="https://user-images.githubusercontent.com/17908917/112412178-0b87ff80-8d59-11eb-9606-e00cfb0070d5.png">


 there's an answer you're looking for ：[https://github.com/pdliuw/ai_barcode/blob/master/example/lib/app_barcode_scanner_widget.dart](https://github.com/pdliuw/ai_barcode/blob/master/example/lib/app_barcode_scanner_widget.dart)
