### ISSUE TITLE
Not able to run or build in IOS

### ISSUE THREAD

**Issue by im-v** [pdliuw/ai_barcode#24]
flutter doctor -v 
![Screenshot 2021-04-10 at 2 53 42 PM](https://user-images.githubusercontent.com/74063024/114265097-8cf3b900-9a0c-11eb-8867-d4a97077e2d6.png)
Error for IOS: - It's generating web files even I am not using this for web.
 
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
2
    Command MergeSwiftModule failed with a nonzero exit code
    __error: /Users/m9/Documents/FlutterInstalation/flutter/.pub-cache/hosted/pub.dartlang.org/ai_barcode_web-2.0.0/ios/Classes/AiBarcodePlugin.h: No such file or directory (in target 'ai_barcode_web' from project 'Pods')__

**Comment by im-v** [comment]
@pdliuw Please let me know if you need more details.

**Comment by pdliuw** [comment]
* please upgrade your flutter version to v2.0.0 or use ai_barcode: 1.2.0 in your pubspec.yaml with flutter v1.22
