### ISSUE TITLE
Camera permission not working in android browser 

### ISSUE THREAD

**Issue by ankitch29** [pdliuw/ai_barcode#27]
Hello,

I am working on a PWA application and I need to scan QR code in my app. I have compiled the code and hosted the web app on firebase, then once I open the link into the android device's browser then it's not asking for camera permissions, hence all the features are blocked in the android browser. Please check the hosted link below on firebase.

[https://scanner-web-16d78.web.app](url)

**Comment by pdliuw** [comment]
* desktop browser is ok!
* we will improve something to adapter android browser

**Comment by tranvanphay** [comment]
> Hello,
> 
> I am working on a PWA application and I need to scan QR code in my app. I have compiled the code and hosted the web app on firebase, then once I open the link into the android device's browser then it's not asking for camera permissions, hence all the features are blocked in the android browser. Please check the hosted link below on firebase.
> 
> [https://scanner-web-16d78.web.app](url)

try this solution to fix this problem. I tried and successfully

**Comment by vrman** [comment]
same here +1
my browser is up to date , chrome and firefox , but its not working on both of them.

**Comment by pdliuw** [comment]
enhancement android browser[ v3.0.1](https://github.com/pdliuw/ai_barcode/releases/tag/v3.0.1)

**Comment by vrman** [comment]
> 
> 
> enhancement android browser[ v3.0.1](https://github.com/pdliuw/ai_barcode/releases/tag/v3.0.1)

what about ios ? safari ? is this work on safari too ?

**Comment by vrman** [comment]
still not working in both ios and android , could you please update example to test this over the mobile browsers  ?

**Comment by ankitch29** [comment]
I have tried with updated source code too, but still not working for me too for any browsers.

**Comment by vrman** [comment]
> 
> 
> I have tried with updated source code too, but still not working for me too for any browsers.

could you tell me how you ask for camera permission in your example ? is this possible to share code with us ?
thanks

**Comment by pdliuw** [comment]
> > 增强 android 浏览器[v3.0.1](https://github.com/pdliuw/ai_barcode/releases/tag/v3.0.1)
> 
> ios呢？苹果浏览器 ？这也适用于 safari 吗？

I tried again. It supports PWA. Can you provide more information about what you have described?

**Comment by pdliuw** [comment]
I tried again. It supports PWA. 

please [click me](https://flutter-app-sample.github.io/#/BarcodeMainPage) see here for more example

**Comment by pdliuw** [comment]
> still not working in both ios and android , could you please update example to test this over the mobile browsers ?

I tried again. It is ok.
if you still can not .please report more detail information about it.

**Comment by pdliuw** [comment]
> I have tried with updated source code too, but still not working for me too for any browsers.

I tried again. It is ok.
if you still can not .please report more detail information about it.

**Comment by pdliuw** [comment]
I tried again. It is ok.
if you still can not .please check your environment or upgrade it.

**Comment by vrman** [comment]
> 
> 
> I tried again. It supports PWA.
> 
> please [click me](https://flutter-app-sample.github.io/#/BarcodeMainPage) see here for more example

could you share this example with us ?

**Comment by vrman** [comment]
problems in pwa are , i hope you fix number 1 :
1- its not support 1d barcode .
2- camera doesnt stop after detect barcode like mobile versions , continue scanning.
3- there is no scan area detection like mobile versions

**Comment by pdliuw** [comment]
> problems in pwa are , i hope you fix number 1 :
> 1- its not support 1d barcode .
> 2- camera doesnt stop after detect barcode like mobile versions , continue scanning.
> 3- there is no scan area detection like mobile versions

you are right,so far it is this.

we will improve it in the future
