### ISSUE TITLE
Finished with error: The plugin ai_barcode could not be built due to the issue above.

### ISSUE THREAD

**Issue by katlehotech** [pdliuw/ai_barcode#3]
Launching lib\main.dart on MAR LX1M in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     C:\Users\Thapelo Radebe\AndroidStudioProjects\paymart\android\app\src\main\res\values\colors.xml:4:2-53: AAPT: error: invalid color.

     C:\Users\Thapelo: AAPT: Radebe\AndroidStudioProjects\paymart\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml: error: file failed to compile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin ai_barcode...
Running Gradle task 'assembleAarRelease'...
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :checkReleaseManifest UP-TO-DATE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :packageReleaseResources UP-TO-DATE
> Task :parseReleaseLibraryResources UP-TO-DATE
> Task :processReleaseManifest UP-TO-DATE
> Task :generateReleaseRFile UP-TO-DATE

> Task :compileReleaseKotlin FAILED

> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders UP-TO-DATE
> Task :generateReleaseAssets UP-TO-DATE
> Task :packageReleaseAssets UP-TO-DATE
> Task :packageReleaseRenderscript NO-SOURCE
> Task :prepareLintJarForPublish UP-TO-DATE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :mergeReleaseNativeLibs UP-TO-DATE
> Task :stripReleaseDebugSymbols UP-TO-DATE
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
16 actionable tasks: 1 executed, 15 up-to-date

e: C:\Users\Thapelo Radebe\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode-1.0.3\android\src\main\kotlin\com\air\ai_barcode\AiBarcodePlugin.kt: (3, 28): Unresolved reference: NonNull
e: C:\Users\Thapelo Radebe\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode-1.0.3\android\src\main\kotlin\com\air\ai_barcode\AiBarcodePlugin.kt: (13, 36): Unresolved reference: NonNull
e: C:\Users\Thapelo Radebe\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode-1.0.3\android\src\main\kotlin\com\air\ai_barcode\AiBarcodePlugin.kt: (46, 30): Unresolved reference: NonNull
e: C:\Users\Thapelo Radebe\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode-1.0.3\android\src\main\kotlin\com\air\ai_barcode\AiBarcodePlugin.kt: (46, 57): Unresolved reference: NonNull
e: C:\Users\Thapelo Radebe\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode-1.0.3\android\src\main\kotlin\com\air\ai_barcode\AiBarcodePlugin.kt: (54, 38): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

Finished with error: The plugin ai_barcode could not be built due to the issue above.

**Comment by pdliuw** [comment]
This plugin adapts to the latest flutter version.

We carried out the migration of androidX according to the prompt of the latest version of flutter,  [androidx-migration](https://flutter.dev/docs/development/androidx-migration)

We recommend that you migrate your project to AndroidX to fix this problem

config: 
`
android.enableR8=true

android.useAndroidX=true

android.enableJetifier=true

`
