### ISSUE TITLE
Camera issue in Web Mobile

### ISSUE THREAD

**Issue by shivangguptaa** [pdliuw/ai_barcode#38]
Cannot scan qr code in flutter web on mobile. The camera does not open in mobile. It works properly on pc but when opened in mobile browser the camera does not open and shows a blank screen.

**Comment by karimi1064** [comment]
Did you solve this issue?

**Comment by pdliuw** [comment]
used for sample : https://flutter-app-sample.github.io/#/BarcodeMainPage

[click me preview effect on your mobile web](https://flutter-app-sample.github.io/#/BarcodeMainPage)

**Comment by karimi1064** [comment]
@pdliuw I successfully scan QR code in flutter web app. But after scanning and get a result, camera preview doesn't stop, even using these commands:
 ```
_scannerController?.stopCameraPreview();
 _scannerController?.stopCamera(); 
```
In mobile version, everything goes OK. My issue is only in web version in stopping camera preview.
