### ISSUE TITLE
java.io.IOException: setPreviewTexture failed

### ISSUE THREAD

**Issue by philos3** [pdliuw/ai_barcode#4]
I/Camera  (28740): open camera: 0, package name: com.radi.flutterbeauty
I/HwCameraUtil(28740): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
E/Camera  (28740): Error 2
I/Camera  (28740): open camera: 0, package name: com.radi.flutterbeauty
I/HwCameraUtil(28740): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
E/CameraPreview(28740): java.io.IOException: setPreviewTexture failed
E/CameraPreview(28740): java.io.IOException: setPreviewTexture failed
E/CameraPreview(28740): 	at android.hardware.Camera.setPreviewSurface(Native Method)
E/CameraPreview(28740): 	at android.hardware.Camera.setPreviewDisplay(Camera.java:772)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:88)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:73)
E/CameraPreview(28740): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:801)
E/CameraPreview(28740): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:162)
E/CameraPreview(28740): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
E/CameraPreview(28740): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2944)
E/CameraPreview(28740): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
E/CameraPreview(28740): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
E/CameraPreview(28740): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
E/CameraPreview(28740): 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
E/CameraPreview(28740): 	at android.view.Choreographer.doFrame(Choreographer.java:776)
E/CameraPreview(28740): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
E/CameraPreview(28740): 	at android.os.Handler.handleCallback(Handler.java:888)
E/CameraPreview(28740): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraPreview(28740): 	at android.os.Looper.loop(Looper.java:213)
E/CameraPreview(28740): 	at android.app.ActivityThread.main(ActivityThread.java:8169)
E/CameraPreview(28740): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraPreview(28740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/CameraPreview(28740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/CameraPreview(28740): java.io.IOException: setPreviewTexture failed
E/CameraPreview(28740): java.io.IOException: setPreviewTexture failed
E/CameraPreview(28740): 	at android.hardware.Camera.setPreviewSurface(Native Method)
E/CameraPreview(28740): 	at android.hardware.Camera.setPreviewDisplay(Camera.java:772)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:88)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.surfaceChanged(CameraPreview.java:73)
E/CameraPreview(28740): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:801)
E/CameraPreview(28740): 	at android.view.SurfaceView.setFrame(SurfaceView.java:377)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22111)
E/CameraPreview(28740): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/CameraPreview(28740): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/CameraPreview(28740): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/CameraPreview(28740): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/CameraPreview(28740): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1839)
E/CameraPreview(28740): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1683)
E/CameraPreview(28740): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1592)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
E/CameraPreview(28740): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/CameraPreview(28740): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:937)
E/CameraPreview(28740): 	at android.view.View.layout(View.java:22114)
E/CameraPreview(28740): 	at android.view.ViewGroup.layout(ViewGroup.java:6335)
E/CameraPreview(28740): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3285)
E/CameraPreview(28740): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2785)
E/CameraPreview(28740): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
E/CameraPreview(28740): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
E/CameraPreview(28740): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
E/CameraPreview(28740): 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
E/CameraPreview(28740): 	at android.view.Choreographer.doFrame(Choreographer.java:776)
E/CameraPreview(28740): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
E/CameraPreview(28740): 	at android.os.Handler.handleCallback(Handler.java:888)
E/CameraPreview(28740): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraPreview(28740): 	at android.os.Looper.loop(Looper.java:213)
E/CameraPreview(28740): 	at android.app.ActivityThread.main(ActivityThread.java:8169)
E/CameraPreview(28740): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraPreview(28740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/CameraPreview(28740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/Camera  (28740): Error 2
E/CameraPreview(28740): java.lang.RuntimeException: cancelAutoFocus failed
E/CameraPreview(28740): java.lang.RuntimeException: cancelAutoFocus failed
E/CameraPreview(28740): 	at android.hardware.Camera.native_cancelAutoFocus(Native Method)
E/CameraPreview(28740): 	at android.hardware.Camera.cancelAutoFocus(Camera.java:1466)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:120)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraPreview.surfaceDestroyed(CameraPreview.java:79)
E/CameraPreview(28740): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:740)
E/CameraPreview(28740): 	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:281)
E/CameraPreview(28740): 	at android.view.View.dispatchDetachedFromWindow(View.java:19781)
E/CameraPreview(28740): 	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5707)
E/CameraPreview(28740): 	at android.view.ViewGroup.removeAllViews(ViewGroup.java:5653)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.BarcodeScannerView.setupLayout(BarcodeScannerView.java:78)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:185)
E/CameraPreview(28740): 	at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
E/CameraPreview(28740): 	at android.os.Handler.handleCallback(Handler.java:888)
E/CameraPreview(28740): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraPreview(28740): 	at android.os.Looper.loop(Looper.java:213)
E/CameraPreview(28740): 	at android.app.ActivityThread.main(ActivityThread.java:8169)
E/CameraPreview(28740): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraPreview(28740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/CameraPreview(28740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by pdliuw** [comment]
We take this issue very seriously,
In order to fix this problem faster, can you provide us with more logs?
For example: equipment information, operating environment, application scenarios, carrying system and other information
