### ISSUE TITLE
Android ERROR : ai_barcode_web-2.0.0\android does not exist

### ISSUE THREAD

**Issue by ABDULKARIMALBAIK** [pdliuw/ai_barcode#46]
I am using ai_barcode to androidplatform but it is throwing this error : 
ai_barcode_web-2.0.0\android does not exist

A problem occurred evaluating root project 'android'.
> Basedir D:\Flutter SDK 2\flutter\.pub-cache\hosted\pub.dartlang.org\ai_barcode_web-2.0.0\android does not exist

I used ai_barcode with version 3.0.0 but same error 

Please Give me a solution !!!!

Info; it is running on web platform but it isn't running on andorid  ?????

**Comment by pdliuw** [comment]
[fixed](https://pub.dev/packages/ai_barcode)
