### ISSUE TITLE
Not working for targetSdkVersion > 28

### ISSUE THREAD

**Issue by shivam-modi** [pdliuw/ai_barcode#49]
I am using the package for QR scanning. It works fine in the target SDK version less than equal to 28. But doesn't work for target SDK version greater than 28. Although camera opens, scanning works but the scanner window doesn't appear in web.
![Screenshot_20211202-174208](https://user-images.githubusercontent.com/54451099/144420080-54564f90-12d3-4700-9316-056f9a052395.jpg)
.

**Comment by pdliuw** [comment]
[fixed](https://pub.dev/packages/ai_barcode)
