### ISSUE TITLE
这是我遇见最恐怖的一个库

### ISSUE THREAD

**Issue by pheromone** [pdliuw/ai_barcode#52]
这是我遇见最恐怖的一个库，不知道为啥？集成了，Android是好的，iOS没反应，什么错误也不报。然后三天两头的build失败，还是间歇性的，搞得我怀疑人生了。。。。

**Comment by Kakukaho** [comment]
哈哈

**Comment by a371057600** [comment]
我这边直接是Android拉不起来了,把它注释掉就一切正常,不知道哪里冲突了.

**Comment by pdliuw** [comment]
[fixed](https://pub.dev/packages/ai_barcode)
