### ISSUE TITLE
无法显示预览/识别条码 3.1.0版本

### ISSUE THREAD

**Issue by 823546371** [pdliuw/ai_barcode#62]
更新到新版之后开启预览之后直接覆盖布局，也无法显示预览/识别'条码'

**Comment by artu-st** [comment]
After this update, the tool does not work correctly.

I explain:
- The box that marks the area to scan the code disappears.
- my elements overlapping with a Stack also disappear.
- When scanning a code, the function does not execute correctly.

**Comment by pdliuw** [comment]
[fixed](https://pub.dev/packages/ai_barcode)
