### ISSUE TITLE
[BUG] MissingPluginException(No implementation found for method listen on channel view_type_id_scanner_view_event_channel)

### ISSUE THREAD

**Issue by zhgwu** [pdliuw/ai_barcode#73]
It work in android but in IOS it show blank screen.

Device: iPhone 11 IOS 15.0.2
Package: ai_barcode v3.2.4

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
![Screen Shot 2022-10-06 at 10 08 48](https://user-images.githubusercontent.com/48649647/194206009-fbe7c543-d41b-4f86-b761-017e24053f7d.png)

**Comment by xyhuangjia** [comment]
我也遇到这个问题了，大佬怎么解决的

**Comment by zhgwu** [comment]
> 我也遇到这个问题了，大佬怎么解决的

Add delay before startCamera work with me.

```dart
@override
  void onInit() async {
    scannerController = ScannerController(
        scannerResult: onScannedData,
        scannerViewCreated: () async {
          if (Platform.isIOS) {
            await Future.delayed(
              const Duration(milliseconds: 300),
            );
          }
          scannerController?.startCamera();
          scannerController?.startCameraPreview();
          //_isFlashOn(scannerController?.isOpenFlash);
        });
    super.onInit();
  }
```
