### ISSUE TITLE
About the crash on ios13.x.x

### ISSUE THREAD

**Issue by Benx4001** [pdliuw/ai_barcode#8]
when I use the plugin on ios 12, the result is perfect. 
And after i upgrade my system to 13 even 14 beta, the issue happens that when i start camera, the response getting slower and slower and at last it crashes. 
But when i just go into the same page again and the speed get quicker again.  So anyone ever meet the same issue?
 
waiting online...

**Comment by pdliuw** [comment]
After preliminary investigation, this problem has not been found. We look forward to your more detailed log
